var Global=Global||{};Global.CardObj=null;Global.CardObjContainer=null;
var Card=Card||new Class({Implements:[Options],options:{container:null,lineLengths:[],requiredLineLengthsPx:[],selectListElement:null,selectListIndex:null,textInput:null},element:null,initialize:function(b){this.setOptions(b);this.element=this.options.container;Global.CardObjContainer=this.options.container},load:function(){var b=this;(new Request.JSON({url:b.options.uri+".js",method:"get",onFailure:function(a){throw"Error getting images: "+a.responseText;},onSuccess:function(a){Object.keys(a).each(function(c){b.options[c]=
a[c]});b.options.requiredLineLengthsPx=b.options.line_lengths;b.initElement()}})).send();return this},dispose:function(){this.options.container.set("html","")},toHtml:function(){return this.element},getText:function(){return this.options.textInput.element.get("value")},initElement:function(){this.illustrationElement=new Element("img",{src:this.options.uri,id:"illustration",styles:{top:this.options.illustration_top_px+"px"}});this.element.adopt(this.illustrationElement);this.options.textInput=new Card.Text(this.options);
this.element.adopt(this.options.textInput.toHtml());this.options.textInput.replaceUserText();this.options.textInput.element.fireEvent("keyup")}});
Card.Text=Card.Text||new Class({Implements:[Options],options:{container:null,requiredLineLengthsPx:null,userText:null},oldValue:null,running:!1,element:null,spaceWidth:null,initialize:function(b){this.setOptions(b);var a=this;a.spaceWidth=a.getChrWidth(" ");this.element=new Element("textarea",{"class":"card_text",styles:{fontSize:a.options.font_size_px+"px",lineSpacing:a.options.font_size_px+a.options.leading+"px"},text:a.options.text||"Type here",events:{focus:function(){a.element.value.contains("Type here")&&
(a.element.value="")},keydown:function(b){a.oldValue=b.target.value},keyup:function(){if(a.oldValue!=a.element.value&&!a.running){a.running=!0;var b=a.element.getCaretPosition(),e=b==a.element.get("value").length;a.oldValue=a.element.value;a.element.set("value",a.flow(a.element.get("value")));e&&(b=a.element.get("value").length);a.element.setCaretPosition(b);a.running=!1}}}})},toHtml:function(){return this.element},replaceUserText:function(){this.options.userText&&this.options.textInput.element.set("value",
this.options.userText)},flow:function(b){var a="",c=1,e="",d=0,f,b=b.replace(/\r/g," "),b=b.replace(/(\S+)\r(\S+)/g,function(a,b,c){return b+" "+c}),b=b.replace(/(\s+)\r(\S+)/g,function(a,b,c){return b+c}),b=b.replace(/(\S+)\r(\s+)/g,function(a,b,c){return b+c});b.match(/\s$/);for(var j=RegExp(/(\S+)(\s+)?/g);f=j.exec(b);){var g=f[1],h=f[2],i=""==g?0:this.getChrWidth(g);f=d+this.spaceWidth+i;i&&(f>this.options.requiredLineLengthsPx[c-1]?c<=this.options.requiredLineLengthsPx.length&&(a+=e+"\r"+g,e=
"",d=0,c++):c<=this.options.requiredLineLengthsPx.length&&(e+=g,d=f));h&&c<=this.options.requiredLineLengthsPx.length&&(h.match(/[\n\r\f]/g)?(a+=e+"\n",e="",d=0,c+=1):(d+=this.spaceWidth*h.length,e+=h))}b=(f=b.match(/^(\s+)/))?f[1]:"";c<=this.options.requiredLineLengthsPx.length&&0<d&&(a+=e);return b+a},getChrWidth:function(b){var b=b.replace(/\s/g,"."),a=new Element("div",{"class":"text",styles:{fontSize:this.options.font_size_px+"px",position:"absolute",left:0,top:-1E3}});a.set("html",b);document.body.adopt(a);
b=a.getDimensions(!0);a.dispose();return b.width}});
Card.Selector=Card.Selector||new Class({Implements:[Options],options:{indexUri:"/make/index.js",saveUri:"/cgi-bin/create-card.cgi",cardUriElement:null,selectCatElement:null,selectPicsElement:null,cardElement:null},initialize:function(b){var a=this;this.setOptions(b);(new Request.JSON({url:a.options.indexUri,method:"get",onFailure:function(a){throw"Error getting images: "+a.responseText;},onSuccess:function(b){a.populate(b);a.setEvents();a.pageLoaded()}})).send()},populate:function(b){var a=this;a.json=
b;var c={};Object.keys(b).each(function(b){"undefined"===typeof c[b]&&(c[b]=!0,a.options.selectCatElement.adopt(new Element("option",{text:b,value:b})))})},pageLoaded:function(){Global.CardObjContainer=this.options.cardElement;this.options.selectCatElement.fireEvent("change");Global.CardObj=new Card({uri:this.options.selectPicsElement.getChildren()[0].get("full"),container:this.options.cardElement});Global.CardObj.load();new Card.SelectColours({element:this.options.selectColoursElement})},setEvents:function(){var b=
this;this.options.selectCatElement.addEvent("change",function(){b.options.selectPicsElement.set("html","");(new Card.CardSelection({cat:this.value,uris:b.json[this.value]})).thumbs.each(function(a){b.options.selectPicsElement.adopt(a.toHtml())})});this.options.saveElement.addEvent("click",function(){var a={user_name:"test",img_uri:Global.CardObj.options.uri,font_colour:"black",text:Global.CardObj.getText(),background_colour:Global.CardObjContainer.getStyle("background-color")};(new Request.JSON({url:b.options.saveUri,
method:"post",data:{json:JSON.encode(a)},onFailure:function(a){throw"Error getting images: "+a.responseText;},onSuccess:function(a){if(a.htmlUri)document.location.href=a.htmlUri;else{var b=new Spinner(document.body,{img:{styles:{background:"url("+a.uri+") no-repeat",width:a.width+"px",height:a.height+"px"}},message:"Right-click and Save background image"});b.show();var d=new Element("p",{"class":"close"});d.adopt(new Element("a",{href:a.uri,text:" View the image ",target:"_blank",styles:{color:"white",
"text-decoration":"none"}}));d.adopt(new Element("span",{text:" / ",styles:{color:"gray"}}));d.adopt(new Element("span",{text:" Back to the card maker ",events:{click:function(){b.hide();b.destroy()}}}));b.content.adopt(d)}}})).send()})}});Card.CardSelection=Card.CardSelection||new Class({Implements:[Options],options:{cat:null,uris:null},thumbs:[],initialize:function(b){var a=this;this.setOptions(b);this.options.uris.each(function(b){a.thumbs.push(new Card.Thumbnail({link:Object.keys(b)[0],thumb:b[Object.keys(b)[0]]}))})}});
Card.Thumbnail=Card.Thumbnail||new Class({Implements:[Options],options:{link:null,thumb:null},element:null,initialize:function(b){var a=this;this.setOptions(b);this.element=new Element("img",{full:a.options.link,src:a.options.thumb,events:{click:function(){Global.CardObj.dispose();Global.CardObj=new Card({uri:a.options.link,container:Global.CardObjContainer,text:Global.CardObj.getText()});Global.CardObj.load()}}})},toHtml:function(){return this.element}});
Card.SelectColours=Card.SelectColours||new Class({Implements:[Options],options:{element:null,colours:"D7D1F8 CEDEF4 B8E2EF D0E6FF C0F7FE BEFEEB CAFFD8 BDF4CB C9DECB CAFEB8 DFFFCA FFFFC8 F7F9D0 FFDFEF FFECEC FFECF5 FDF2FF F1ECFF EAF1FB DBF0F7 CFFEF0 E3FBE9 E7FFDF FFFFE3".split(" ")},initialize:function(b){var a=this;this.setOptions(b);this.options.colours.each(function(b){a.options.element.adopt((new Card.SelectColours.Colour({hex:b})).toHtml())})}});
Card.SelectColours.Colour=Card.SelectColours.Colour||new Class({Implements:[Options],options:{hex:null},element:null,initialize:function(b){var a=this;this.setOptions(b);this.element=new Element("div",{"class":"colour",styles:{backgroundColor:"#"+this.options.hex},events:{click:function(){Global.CardObjContainer.setStyle("background-color","#"+a.options.hex);Global.CardObjContainer.setStyle("border-color","#"+a.options.hex)}}})},toHtml:function(){return this.element}});
